version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - gocritic
    - gocyclo
    - goconst

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/yostos/tiny-task-tool
